//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pallettaro.Revo.i18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MonthsDes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MonthsDes() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pallettaro.Revo.i18n.MonthsDes", typeof(MonthsDes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alla vendemmia che avviene da settembre a ottobre.
        /// </summary>
        public static string m01 {
            get {
                return ResourceManager.GetString("m01", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alle nebbie e brume basse che sono la trasudazione della natura da ottobre a novembre.
        /// </summary>
        public static string m02 {
            get {
                return ResourceManager.GetString("m02", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to al freddo, a volte asciutto, a volte umido, che si fa sentire da novembre a dicembre.
        /// </summary>
        public static string m03 {
            get {
                return ResourceManager.GetString("m03", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alla neve che imbianca la terra da dicembre a gennaio.
        /// </summary>
        public static string m04 {
            get {
                return ResourceManager.GetString("m04", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alle piogge che cadono in genere più copiosamente da gennaio a febbraio.
        /// </summary>
        public static string m05 {
            get {
                return ResourceManager.GetString("m05", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to agli acquazzoni che hanno luogo, e ai venti che seccano la terra da febbraio a marzo.
        /// </summary>
        public static string m06 {
            get {
                return ResourceManager.GetString("m06", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alla fermentazione e allo sviluppo della linfa da marzo ad aprile.
        /// </summary>
        public static string m07 {
            get {
                return ResourceManager.GetString("m07", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alla sbocciatura dei fiori da aprile a maggio.
        /// </summary>
        public static string m08 {
            get {
                return ResourceManager.GetString("m08", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to alla fecondità ridente dei prati e alla raccolta delle messi da maggio a giugno.
        /// </summary>
        public static string m09 {
            get {
                return ResourceManager.GetString("m09", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to all&apos;aspetto delle spighe ondeggianti e delle mietiture dorate che coprono i campi da giugno a luglio.
        /// </summary>
        public static string m10 {
            get {
                return ResourceManager.GetString("m10", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to al calore allo stesso tempo solare e terrestre che infiamma l&apos;aria da luglio ad agosto.
        /// </summary>
        public static string m11 {
            get {
                return ResourceManager.GetString("m11", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ai frutti che il sole dora e fa maturare da agosto a settembre.
        /// </summary>
        public static string m12 {
            get {
                return ResourceManager.GetString("m12", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ai pochi giorni per allineare le decadi alla rivoluzione terrestre.
        /// </summary>
        public static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
    }
}
